
import { GoogleGenAI, Type } from "@google/genai";

/**
 * Service to interact with the Gemini API for plumbing diagnostics.
 * Always uses the API key from process.env.API_KEY.
 */
export async function getPlumbingAdvice(query: string) {
  // Always use the required initialization pattern with the named parameter.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  try {
    // Calling generateContent with model name and prompt as per guidelines.
    // Using gemini-3-flash-preview for quick troubleshooting and advice.
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Analyze this plumbing issue reported by a customer: "${query}". 
      Provide a diagnosis, severity assessment, and recommendation in a structured format.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            diagnosis: {
              type: Type.STRING,
              description: "A professional explanation of the likely cause.",
            },
            severity: {
              type: Type.STRING,
              enum: ['low', 'medium', 'high', 'emergency'],
              description: "The urgency level of the situation.",
            },
            recommendation: {
              type: Type.STRING,
              description: "Professional advice on immediate next steps.",
            },
          },
          required: ["diagnosis", "severity", "recommendation"],
        },
      },
    });

    // Directly access the .text property from the response object.
    const jsonStr = response.text;
    if (!jsonStr) {
      throw new Error("No response generated by the model.");
    }

    return JSON.parse(jsonStr.trim());
  } catch (error) {
    console.error("Gemini AI Diagnostics Error:", error);
    // Graceful fallback for the user interface.
    return {
      diagnosis: "We encountered an issue analyzing your request.",
      severity: "high",
      recommendation: "Please call our emergency line at (555) 775-8622 for immediate professional help."
    };
  }
}
